In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df = pd.read_csv(r'https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv')
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:
df.drop(columns=['customerID'], inplace=True)

In [6]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [7]:
cat_cols = []
for i in df.columns:
    if df[i].dtype == 'object':
        cat_cols.append(i)

In [8]:
cat_cols

['gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'Churn']

In [9]:
for i in cat_cols:
    print(f'{i} : {df[i].nunique()}')

gender : 2
Partner : 2
Dependents : 2
PhoneService : 2
MultipleLines : 3
InternetService : 3
OnlineSecurity : 3
OnlineBackup : 3
DeviceProtection : 3
TechSupport : 3
StreamingTV : 3
StreamingMovies : 3
Contract : 3
PaperlessBilling : 2
PaymentMethod : 4
Churn : 2

In [10]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [11]:
df['charges_per_month_ratio'] = df['MonthlyCharges'] / (df['tenure'] + 1)
df['is_new_customer'] = (df['tenure'] <= 3).astype(int)

In [12]:
df = pd.get_dummies(df, dtype=int, drop_first=True)

In [13]:
df

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,charges_per_month_ratio,is_new_customer,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,0,1,29.85,29.85,14.925000,1,0,1,0,0,...,0,0,0,0,0,1,0,1,0,0
1,0,34,56.95,1889.50,1.627143,0,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0
2,0,2,53.85,108.15,17.950000,1,1,0,0,1,...,0,0,0,0,0,1,0,0,1,1
3,0,45,42.30,1840.75,0.919565,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,0,2,70.70,151.65,23.566667,1,0,0,0,1,...,0,0,0,0,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,84.80,1990.50,3.392000,0,1,1,1,1,...,1,0,1,1,0,1,0,0,1,0
7039,0,72,103.20,7362.90,1.413699,0,0,1,1,1,...,1,0,1,1,0,1,1,0,0,0
7040,0,11,29.60,346.45,2.466667,0,0,1,1,0,...,0,0,0,0,0,1,0,1,0,0
7041,1,4,74.40,306.60,14.880000,0,1,1,0,1,...,0,0,0,0,0,1,0,0,1,1
7042,0,66,105.65,6844.50,1.576866,0,1,0,0,1,...,1,0,1,0,1,1,0,0,0,0

In [14]:
df.dropna(inplace=True)

In [15]:
X = df.drop(columns=['Churn_Yes'])
y = df['Churn_Yes']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [17]:
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [18]:
y_pred = rf.predict(X_test)

In [19]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.90      0.87      1033
           1       0.65      0.49      0.56       374

    accuracy                           0.79      1407
   macro avg       0.74      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407

In [20]:
churn_probs = rf.predict_proba(X_test)[:,1]
churn_probs

array([0.  , 0.15, 0.68, ..., 0.02, 0.24, 0.  ])

In [21]:


from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, preds)
print(cm)

caught = cm[1,1]
total_flagged = cm[0,1] + cm[1,1]
false_alarms = cm[0,1]
net_value = (cm[1,1] * 2000) - (cm[0,1] * 100)

print(f"Threshold: {threshold}")
print(f"total_flagged: {total_flagged}")
print(f"caught: {caught}")
print(f"false_alarms: {false_alarms}")
print(f"net_value: {net_value}")

NameError: name 'preds' is not defined

Threshold: 0.1
total_flagged: 931
caught: 348
false_alarms: 583
net_value: 637700


Threshold: 0.2
total_flagged: 716
caught: 314
false_alarms: 402
net_value: 587800


Threshold: 0.3
total_flagged: 535
caught: 272
false_alarms: 263
net_value: 517700


Threshold: 0.4
total_flagged: 391
caught: 226
false_alarms: 165
net_value: 435500


Threshold: 0.5
total_flagged: 281
caught: 179
false_alarms: 102
net_value: 347800


Threshold: 0.6
total_flagged: 205
caught: 144
false_alarms: 61
net_value: 281900


Threshold: 0.7
total_flagged: 127
caught: 95
false_alarms: 32
net_value: 186800


Threshold: 0.8
total_flagged: 77
caught: 58
false_alarms: 19
net_value: 114100


Threshold: 0.9
total_flagged: 36
caught: 32
false_alarms: 4
net_value: 63600

In [ ]:
def churn_report(threshold, capacity=None):
    preds = (churn_probs >= threshold).astype(int)
    cm = confusion_matrix(y_test, preds)
    caught = cm[1,1]
    total_flagged = cm[0,1] + cm[1,1]
    false_alarms = cm[0,1]
    net_value = (cm[1,1] * 2000) - (cm[0,1] * 100)

    print(f"Threshold: {threshold}")
    print(f"total_flagged: {total_flagged}")
    print(f"caught: {caught}")
    print(f"false_alarms: {false_alarms}")
    print(f"net_value: {net_value}\n")
    
    if capacity != None:
        if total_flagged > capacity:
            print(f'⚠️ WARNING: {total_flagged} customers flagged exceeds team capacity of {capacity}!')
        else:
            print('✅ Within team capacity.')
    print(f"----------------------------------------------------------------------------------------\n\n")

for i in range(1,10):
    churn_report(i/10, 300)

Threshold: 0.1
total_flagged: 931
caught: 348
false_alarms: 583
net_value: 637700

⚠️ WARNING: 931 customers flagged exceeds team capacity of 300!
----------------------------------------------------------------------------------------


Threshold: 0.2
total_flagged: 716
caught: 314
false_alarms: 402
net_value: 587800

⚠️ WARNING: 716 customers flagged exceeds team capacity of 300!
----------------------------------------------------------------------------------------


Threshold: 0.3
total_flagged: 535
caught: 272
false_alarms: 263
net_value: 517700

⚠️ WARNING: 535 customers flagged exceeds team capacity of 300!
----------------------------------------------------------------------------------------


Threshold: 0.4
total_flagged: 391
caught: 226
false_alarms: 165
net_value: 435500

⚠️ WARNING: 391 customers flagged exceeds team capacity of 300!
----------------------------------------------------------------------------------------


Threshold: 0.5
total_flagged: 281
caught: 179
false_alarms: 102
net_value: 347800

✅ Within team capacity.
----------------------------------------------------------------------------------------


Threshold: 0.6
total_flagged: 205
caught: 144
false_alarms: 61
net_value: 281900

✅ Within team capacity.
----------------------------------------------------------------------------------------


Threshold: 0.7
total_flagged: 127
caught: 95
false_alarms: 32
net_value: 186800

✅ Within team capacity.
----------------------------------------------------------------------------------------


Threshold: 0.8
total_flagged: 77
caught: 58
false_alarms: 19
net_value: 114100

✅ Within team capacity.
----------------------------------------------------------------------------------------


Threshold: 0.9
total_flagged: 36
caught: 32
false_alarms: 4
net_value: 63600

✅ Within team capacity.
----------------------------------------------------------------------------------------